server:
  port: 8090

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:16379}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
            allowed-methods: '*'
            allowed-headers: '*'
            allow-credentials: true
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
